[package]
name = "launchpad"
version = "0.1.0"
authors = ["Sminc"]
edition = "2018"

[dependencies]
anyhow = "1"
thiserror = "1"
tungstenite = "0.10"
winapi = { version = "0.3", features = ["mmeapi", "mmsystem"] }

[profile.release]
lto = true
codegen-units  =1